# Configuration for the movie service
movie:
  replicaCount: 3
  image:
    repository: benjaminbarral/jenkins_movie_service
    pullPolicy: IfNotPresent
    tag: 
  service:
    type: NodePort
    port: 80
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentag: 

# Configuration for the cast service
cast:
  replicaCount: 3
  image:
    repository: benjaminbarral/jenkins_cast_service
    pullPolicy: IfNotPresent
    tag: 
  service:
    type: NodePort
    port: 80
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentag: 

# Common configuration for both services
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
