apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapiapp.fullname" . }}
  labels:
    {{- include "fastapiapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default 8000 }}
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "fastapiapp.selectorLabels" . | nindent 4 }}
