---
# Configuration générale
fullnameOverride: ""  # Laisser vide pour permettre des noms uniques par release
nameOverride: ""      # Nom simplifié pour l'application

# Configuration des réplicas
replicaCount: 3

# Configuration des images Docker
image:
  repository: "benjaminbarral/jenkins_movie_service"
  # Image pour le déploiement
  pullPolicy: IfNotPresent
  tag: "v.3.0"

# Secrets pour tirer des images Docker (optionnel)
imagePullSecrets: []
# Exemple si nécessaire :
# imagePullSecrets:
#   - name: "docker-secret"

# Compte service
serviceAccount:
  create: true
  name: ""  # Nom spécifique à chaque release

# Annotations et labels pour les pods
podAnnotations: {}
podLabels: {}

# Contexte de sécurité pour les pods
podSecurityContext: {}
securityContext: {}

# Configuration des services
service:
  type: NodePort
  port: 80
  targetPort: 8000
  # Laissez `nodePort` vide pour une attribution dynamique
  nodePort: null

# Configuration de l'ingress (désactivé par défaut)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Configuration des ressources
resources: {}
# Exemple si nécessaire :
# resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

# Autoscaling
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Sélecteurs pour les nœuds et tolérances
nodeSelector: {}
tolerations: []
affinity: {}

# Configuration spécifique par namespace (facultatif)
# Vous pouvez définir des `nodePorts` spécifiques pour chaque namespace ici, si nécessaire.
namespaces:
  dev:
    movie:
      service:
        nodePort: null
    cast:
      service:
        nodePort: null
  qa:
    movie:
      service:
        nodePort: null
    cast:
      service:
        nodePort: null
  staging:
    movie:
      service:
        nodePort: null
    cast:
      service:
        nodePort: null
  prod:
    movie:
      service:
        nodePort: null
    cast:
      service:
        nodePort: null
