# Configuration générale
fullnameOverride: "" # Laisser vide pour permettre des noms uniques par release
nameOverride: ""     # Nom simplifié pour l'application

# Configuration des réplicas
replicaCount: 3

# Configuration des images Docker
image:
  repository: "benjaminbarral/jenkins_movie_service" # Image par défaut pour le déploiement
  pullPolicy: IfNotPresent
  tag: "v.3.0"

# Secrets pour tirer des images Docker (optionnel)
imagePullSecrets: []
# Exemple si nécessaire :
# imagePullSecrets:
#   - name: "docker-secret"

# Compte service
serviceAccount:
  create: true
  name: "" # Nom spécifique à chaque release

# Annotations et labels pour les pods
podAnnotations: {}
podLabels: {}

# Contexte de sécurité pour les pods
podSecurityContext: {}
securityContext: {}

# Configuration des services
service:
  type: NodePort
  port: 80
  targetPort: 8000
  nodePort: null # Cette clé sera remplacée par les valeurs spécifiques au namespace

# Configuration de l'ingress (désactivé par défaut)
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Configuration des ressources (laisser vide pour utiliser les valeurs par défaut du cluster)
resources: {}
# Exemple si nécessaire :
# resources:
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

# Autoscaling (désactivé par défaut)
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Sélecteurs pour les nœuds et tolérances
nodeSelector: {}
tolerations: []
affinity: {}

# Configuration spécifique par namespace
namespaces:
  dev:
    movie:
      service:
        nodePort: 30010
    cast:
      service:
        nodePort: 30012
  qa:
    movie:
      service:
        nodePort: 30020
    cast:
      service:
        nodePort: 30022
  staging:
    movie:
      service:
        nodePort: 30030
    cast:
      service:
        nodePort: 30032
  prod:
    movie:
      service:
        nodePort: 30040
    cast:
      service:
        nodePort: 30042
